### ISSUE TITLE
The rating system is broken.

### ISSUE THREAD

**Issue by convenient** [njall/pretentious-o-meter#21]
See: [http://pretentious-o-meter.co.uk/?q=Fired+Up!](http://pretentious-o-meter.co.uk/?q=Fired+Up!)

Clearly this is not a "Rubbish Film".

![](http://i.imgur.com/f7jERdp.png)

**Comment by njall** [comment]
Hmm.. I see. Looks like an error. [I've patched the bug](http://pretentious-o-meter.co.uk/?q=Fired+Up!)

**Comment by convenient** [comment]
Panther meat!
